<!-- MeadCo Security Manager -->
<object viewastext style="display:none"
  id="secmgr"
  classid="clsid:5445be81-b796-11d2-b931-002018654e2e"
  codebase="http://pfcintranet/PrintPro/smsx.cab#Version=6,6,440.22">
  <param name="GUID" value="{B02F4950-6F28-45B3-8ED2-9D65A91CCD28}">
  <param name="Path" value="http://pfcintranet/PrintPro/sxlic.mlf">
  <param name="Revision" value="2">
  <param name="PerUser" value="true">
</object>
 
<!-- MeadCo ScriptX -->
<object viewastext id="factory" style="display:none"
  classid="clsid:1663ed61-23eb-11d2-b92f-008048fdd814">
</object>
