robocopy \\pfcintranet\e$\Intranet-PFC "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\Intranet-PFC"/"" /MIR /COPYALL /XF *.xls* *.zip *.xml *.pdf *.btw *.ppt* *.psd* *.doc* *old_*.* *.*_old* "Copy of*.*" cas*m.htm* /XD \\pfcintranet\e$\Intranet-PFC\CriticalItemRpt_old \\pfcintranet\e$\Intranet-PFC\Common\Images_old
robocopy \\pfcintranet\e$\Software\PFCApps\IntranetSite\ "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\IntranetSite"/"" /MIR /COPYALL /XF *.xls* *.zip *.xml *.pdf *.btw *.ppt* *.psd* *.doc* *old_*.* *.*_old* "Copy of*.*" cas*m.htm* /XD \\pfcintranet\e$\Software\PFCApps\IntranetSite\TDixon_DELETE \\pfcintranet\e$\Software\PFCApps\IntranetSite\Websitelog \\pfcintranet\e$\Software\PFCApps\IntranetSite\MarketingManagement\website_log_files \\pfcintranet\e$\Software\PFCApps\IntranetSite\CustomerActivitySheet\temp \\pfcintranet\e$\Software\PFCApps\IntranetSite\FantasyFootballold \\pfcintranet\e$\Software\PFCApps\IntranetSite\InvReportDashboard\oldVersions
robocopy \\pfcintranet\e$\Software\PFCApps\POE\ "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\POE"/"" /MIR /COPYALL /XF *.xls* *.zip *.xml *.pdf *.btw *.ppt* *.psd* *.doc* *old_*.* *.*_old* "Copy of*.*" cas*m.htm* /XD \\pfcintranet\e$\Software\PFCApps\POE\TempPage
robocopy \\pfcwebapp2\c$\Software\PFCApps\SOE\ "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\SOE"/"" /MIR /COPYALL /XF *.xls* *.zip *.xml *.pdf *.btw *.ppt* *.psd* *.doc* *old_*.* *.*_old* "Copy of*.*" cas*m.htm* /XD \\pfcwebapp2\c$\Software\PFCApps\SOE\ERPCreditMemo \\pfcwebapp2\c$\Software\PFCApps\SOE\ERPInvoice \\pfcwebapp2\c$\Software\PFCApps\SOE\ERPReturnAuthorization \\pfcwebapp2\c$\Software\PFCApps\SOE\ERPReturnReceipt \\pfcwebapp2\c$\Software\PFCApps\SOE\InvoiceFile \\pfcwebapp2\c$\Software\PFCApps\SOE\RollBack \\pfcwebapp2\c$\Software\PFCApps\SOE\SOEShipper \\pfcwebapp2\c$\Software\PFCApps\SOE\Common\Images\tempimages \\pfcwebapp2\c$\Software\PFCApps\SOE\Common\TempPages
robocopy \\pfcwebapp2\c$\Software\PFCApps\WOE\ "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\WOE"/"" /MIR /COPYALL /XF *.xls* *.zip *.xml *.pdf *.btw *.ppt* *.psd* *.doc* *old_*.* *.*_old* "Copy of*.*" cas*m.htm*
copy "\\pfcdata\users\tod\My Documents\_Projects\Project Tracking\Project Tracking.xls" "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\"
del "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\IntranetSite\CPR\Excel\*.*" /Q
del "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\IntranetSite\SalesAnalysisReport\QuoteExport\*.txt" /Q
del "C:\Documents and Settings\tod\My Documents\My Dropbox\Software\PFCApps\IntranetSite\CPR\Excel\*.*" /Q
