Select
------	'9000'+RIGHT([No_],6)	 as	OrderNo,
	[No_]			 as 	InvoiceNo	,
	[Sell-to Customer No_]	 as 	SellToCustNo	,
	[Bill-to Customer No_]	 as 	BillToCustNo	,
	[Bill-to Name]		 as 	BillToCustName	,
	[Bill-to Address]	 as 	BillToAddress1	,
	[Bill-to Address 2]	 as 	BillToAddress2	,
	[Bill-to City]		 as 	BillToCity	,
	[Bill-to Contact]	 as 	BillToContactName	,
	[Your Reference]	 as 	BillToAddress3	,
	[Ship-to Code]		 as 	ShipToCd	,
	[Ship-to Name]		 as 	ShipToName	,
	[Ship-to Name 2]	 as 	ShipToAddress3	,
	[Ship-to Address]	 as 	ShipToAddress1	,
	[Ship-to Address 2]	 as 	ShipToAddress2	,
	[Ship-to City]		 as 	City	,
	[Ship-to Contact]	 as 	ContactName	,
------	[Order Date]		 as 	OrderDt	,
	[Posting Date]		 as 	ArPostDt	,
	[Shipment Date]		 as 	SchShipDt	,
	[Payment Terms Code]	 as 	OrderTermsCd	,
	[Due Date]		 as 	OrderPromDt	,
	[Payment Discount %]	 as 	DiscPct	,
--	[Pmt_ Discount Date]	 as 		,
	[Shipment Method Code]	 as 	OrderMethCd	,
	[Location Code]		 as 	ShipLoc	,
--	[Customer Price Group]	 as 		,
	[Invoice Disc_ Code]	 as 	DiscountCd	,
--	[Customer Disc_ Group]	 as 		,
	[Salesperson Code]	 as 	SalesRepNo	,
------	[Order No_]		 as 	OrderNo	,
	[No_ Printed]		 as 	CopiestoPrint	,
--	[On Hold]		 as 		,
--	[VAT Country Code]	 as 		,
	[Sell-to Customer Name]	 as 	SellToCustName	,
	[Sell-to Address]	 as 	SellToAddress1	,
	[Sell-to Address 2]	 as 	SellToAddress2	,
	[Sell-to City]		 as 	SellToCity	,
	[Sell-to Contact]	 as 	SellToContactName	,
	[Bill-to Post Code]	 as 	BillToZip	,
	[Bill-to County]	 as 	BillToState	,
	[Bill-to Country Code]	 as 	BillToCountry	,
	[Sell-to Post Code]	 as 	SellToZip	,
	[Sell-to County]	 as 	SellToState	,
	[Sell-to Country Code]	 as 	SellToCountry	,
	[Ship-to Post Code]	 as 	Zip	,
	[Ship-to County]	 as 	State	,
	[Ship-to Country Code]	 as 	Country	,
--	[Bal_ Account Type]	 as 		,
--	[Document Date]		 as 		,
	[External Document No_]	 as 	ReferenceNo	,
--	[Payment Method Code]	 as 		,
------	[Shipping Agent Code]	 as 	OrderCarName	,
--	[Package Tracking No_]	 as 		,
--	[User ID]		 as 	EntryId  (or load with Entered User ID)	,
--	[Source Code]		 as 		,
	[Sell-to Contact No_]	 as 	SellToContactPhoneNo	,
	[Bill-to Contact No_]	 as 	BillToContactPhoneNo	,
--	[Allow Line Disc_]	 as 		,
--	[Tax Exemption No_]	 as 		,
	[Usage Location]	 as 	UsageLoc	,
	[Sales Location]	 as 	OrderLoc	,
------	[Order Type]		 as 	OrderType	,
	'51'			 as 	OrderType	,
	'Credit Memo'		 as	OrderTypeDsc,	
--	[E-Ship Agent Service]	 as 		,
--	[Free Freight]		 as 		,
--	[COD Payment]		 as 		,
--	[World Wide Service]	 as 		,
--	[Shipping Payment Type]	 as 		,
--	[Third Party Ship_ Account No_]	 as 		,
--	[Shipping Insurance]	 as 		,
--	[Ship-for Code]		 as 		,
--	[External Sell-to No_]	 as 		,
--	[External Ship-to No_]	 as 		,
--	[External Ship-for No_]	 as 		,
--	[Invoice for Bill of Lading No_]	 as 		,
	[Entered User ID]	 as 	EntryId	,
	[Entered Time]		 as 	EntryDt	,
	[Inside Salesperson Code]	 as 	CustSvcRepName	,
	[Phone No_]		 as 	PhoneNo	,
	[Fax No_]		 as 	FaxNo	
FROM	[Porteous$Sales Cr_Memo Header]
--Where LEFT([No_],3)='SCR'
Order by [No_]