SELECT	COUNT(AlternatePrice ) as AlternatePrice	 	FROM SODetailHist WHERE AlternatePrice  is not null
SELECT	COUNT(AlternateUM ) as AlternateUM 			FROM SODetailHist WHERE AlternateUM  is not null
SELECT	COUNT(AlternateUMQty ) as AlternateUMQty	 	FROM SODetailHist WHERE AlternateUMQty  is not null
SELECT	COUNT(BinLoc ) as BinLoc 				FROM SODetailHist WHERE BinLoc  is not null
SELECT	COUNT(CarrierCd ) as CarrierCd 				FROM SODetailHist WHERE CarrierCd  is not null
SELECT	COUNT(ChangeDate ) as ChangeDate 			FROM SODetailHist WHERE ChangeDate  is not null
SELECT	COUNT(ChangeID ) as ChangeID 				FROM SODetailHist WHERE ChangeID  is not null
SELECT	COUNT(CostInd ) as CostInd 				FROM SODetailHist WHERE CostInd  is not null
SELECT	COUNT(DiscPct1 ) as DiscPct1 				FROM SODetailHist WHERE DiscPct1  is not null
SELECT	COUNT(DiscUnitPrice ) as DiscUnitPrice 			FROM SODetailHist WHERE DiscUnitPrice  is not null
SELECT	COUNT(ExcludedFromUsageFlag ) as ExcludedFromUsageFlag 	FROM SODetailHist WHERE ExcludedFromUsageFlag  is not null
SELECT	COUNT(FreightCd ) as FreightCd 				FROM SODetailHist WHERE FreightCd  is not null
SELECT	COUNT(IMLoc ) as IMLoc 					FROM SODetailHist WHERE IMLoc  is not null
SELECT	COUNT(LineExpdCd ) as LineExpdCd 			FROM SODetailHist WHERE LineExpdCd  is not null
SELECT	COUNT(LineExpdCdDsc ) as LineExpdCdDsc 			FROM SODetailHist WHERE LineExpdCdDsc  is not null
SELECT	COUNT(LinePriceInd ) as LinePriceInd 			FROM SODetailHist WHERE LinePriceInd  is not null
SELECT	COUNT(LineReason ) as LineReason 			FROM SODetailHist WHERE LineReason  is not null
SELECT	COUNT(LineReasonDsc ) as LineReasonDsc 			FROM SODetailHist WHERE LineReasonDsc  is not null
SELECT	COUNT(LineSeq ) as LineSeq 				FROM SODetailHist WHERE LineSeq  is not null
SELECT	COUNT(LineType ) as LineType 				FROM SODetailHist WHERE LineType  is not null
SELECT	COUNT(LISource ) as LISource 				FROM SODetailHist WHERE LISource  is not null
SELECT	COUNT(OECost ) as OECost 				FROM SODetailHist WHERE OECost  is not null
SELECT	COUNT(OriginalQtyRequested ) as OriginalQtyRequested 	FROM SODetailHist WHERE OriginalQtyRequested  is not null
SELECT	COUNT(PriceCd ) as PriceCd 				FROM SODetailHist WHERE PriceCd  is not null
SELECT	COUNT(QtyAvail1 ) as QtyAvail1 				FROM SODetailHist WHERE QtyAvail1  is not null
SELECT	COUNT(QtyAvail2 ) as QtyAvail2 				FROM SODetailHist WHERE QtyAvail2  is not null
SELECT	COUNT(QtyAvail3 ) as QtyAvail3 				FROM SODetailHist WHERE QtyAvail3  is not null
SELECT	COUNT(QtyAvailLoc1 ) as QtyAvailLoc1 			FROM SODetailHist WHERE QtyAvailLoc1  is not null
SELECT	COUNT(QtyAvailLoc2 ) as QtyAvailLoc2 			FROM SODetailHist WHERE QtyAvailLoc2  is not null
SELECT	COUNT(QtyAvailLoc3 ) as QtyAvailLoc3 			FROM SODetailHist WHERE QtyAvailLoc3  is not null
SELECT	COUNT(QtyBO ) as QtyBO 					FROM SODetailHist WHERE QtyBO  is not null
SELECT	COUNT(RepCost ) as RepCost 				FROM SODetailHist WHERE RepCost  is not null
SELECT	COUNT(RqstdShipDt ) as RqstdShipDt 			FROM SODetailHist WHERE RqstdShipDt  is not null
SELECT	COUNT(SellStkFactor ) as SellStkFactor 			FROM SODetailHist WHERE SellStkFactor  is not null
SELECT	COUNT(SellStkQty ) as SellStkQty 			FROM SODetailHist WHERE SellStkQty  is not null
SELECT	COUNT(SellStkUM ) as SellStkUM 				FROM SODetailHist WHERE SellStkUM  is not null
SELECT	COUNT(StatusCd ) as StatusCd 				FROM SODetailHist WHERE StatusCd  is not null
SELECT	COUNT(SuperEquivQty ) as SuperEquivQty 			FROM SODetailHist WHERE SuperEquivQty  is not null
SELECT	COUNT(SuperEquivUM ) as SuperEquivUM 			FROM SODetailHist WHERE SuperEquivUM  is not null
SELECT	COUNT(UnitCost2 ) as UnitCost2 				FROM SODetailHist WHERE UnitCost2  is not null
SELECT	COUNT(UnitCost3 ) as UnitCost3 				FROM SODetailHist WHERE UnitCost3  is not null
SELECT	COUNT(UsageLoc ) as UsageLoc 				FROM SODetailHist WHERE UsageLoc  is not null
