SELECT	COUNT(AllocRelDt) as AllocRelDt 		FROM SOHeaderHist WHERE AllocRelDt  is  not null
SELECT	COUNT(BOLWght) as BOLWght 			FROM SOHeaderHist WHERE BOLWght  is not null
SELECT	COUNT(BranchReqDt) as BranchReqDt 		FROM SOHeaderHist WHERE BranchReqDt  is not null
SELECT	COUNT(ChangeDt) as ChangeDt 			FROM SOHeaderHist WHERE ChangeDt  is not null
SELECT	COUNT(ChangeID) as ChangeID 			FROM SOHeaderHist WHERE ChangeID  is not null
SELECT	COUNT(CommDol) as CommDol 			FROM SOHeaderHist WHERE CommDol  is not null
SELECT	COUNT(CustPONo) as CustPONo 			FROM SOHeaderHist WHERE CustPONo  is not null
SELECT	COUNT(CustReqDt) as CustReqDt 			FROM SOHeaderHist WHERE CustReqDt  is not null
SELECT	COUNT(CustSvcRepName) as CustSvcRepName 	FROM SOHeaderHist WHERE CustSvcRepName  is not null
SELECT	COUNT(CustSvcRepNo) as CustSvcRepNo 		FROM SOHeaderHist WHERE CustSvcRepNo  is not null
SELECT	COUNT(DiscPct) as DiscPct 			FROM SOHeaderHist WHERE DiscPct  is not null
SELECT	COUNT(DocumentSortInd) as DocumentSortInd 	FROM SOHeaderHist WHERE DocumentSortInd  is not null
SELECT	COUNT(fSOHeaderID) as fSOHeaderID 		FROM SOHeaderHist WHERE fSOHeaderID  is not null
SELECT	COUNT(HoldReasonName) as HoldReasonName 	FROM SOHeaderHist WHERE HoldReasonName  is not null
SELECT	COUNT(MakeOrderDt) as MakeOrderDt 		FROM SOHeaderHist WHERE MakeOrderDt  is not null
SELECT	COUNT(NonTaxAmt) as NonTaxAmt 			FROM SOHeaderHist WHERE NonTaxAmt  is not null
SELECT	COUNT(OrderCarName) as OrderCarName 		FROM SOHeaderHist WHERE OrderCarName  is not null
SELECT	COUNT(OrderCarrier) as OrderCarrier 		FROM SOHeaderHist WHERE OrderCarrier  is not null
SELECT	COUNT(OrderDt) as OrderDt 			FROM SOHeaderHist WHERE OrderDt  is not null
SELECT	COUNT(OrderExpdCd) as OrderExpdCd 		FROM SOHeaderHist WHERE OrderExpdCd  is not null
SELECT	COUNT(OrderExpdCdName) as OrderExpdCdName 	FROM SOHeaderHist WHERE OrderExpdCdName  is not null
SELECT	COUNT(OrderFreightCd) as OrderFreightCd 	FROM SOHeaderHist WHERE OrderFreightCd  is not null
SELECT	COUNT(OrderFreightName) as OrderFreightName 	FROM SOHeaderHist WHERE OrderFreightName  is not null
SELECT	COUNT(OrderLoc) as OrderLoc 			FROM SOHeaderHist WHERE OrderLoc  is not null
SELECT	COUNT(OrderLocName) as OrderLocName 		FROM SOHeaderHist WHERE OrderLocName  is not null
SELECT	COUNT(OrderMethCd) as OrderMethCd 		FROM SOHeaderHist WHERE OrderMethCd  is not null
SELECT	COUNT(OrderMethName) as OrderMethName 		FROM SOHeaderHist WHERE OrderMethName  is not null
SELECT	COUNT(OrderNo) as OrderNo 			FROM SOHeaderHist WHERE OrderNo  is not null
SELECT	COUNT(OrderPriName) as OrderPriName 		FROM SOHeaderHist WHERE OrderPriName  is not null
SELECT	COUNT(OrderPriorityCd) as OrderPriorityCd 	FROM SOHeaderHist WHERE OrderPriorityCd  is not null
SELECT	COUNT(OrderTermsName) as OrderTermsName 	FROM SOHeaderHist WHERE OrderTermsName  is not null
SELECT	COUNT(OrderType) as OrderType 			FROM SOHeaderHist WHERE OrderType  is not null
SELECT	COUNT(OrderTypeDsc) as OrderTypeDsc 		FROM SOHeaderHist WHERE OrderTypeDsc  is not null
SELECT	COUNT(PriceCd) as PriceCd 			FROM SOHeaderHist WHERE PriceCd  is not null
SELECT	COUNT(ReasonCd) as ReasonCd 			FROM SOHeaderHist WHERE ReasonCd  is not null
SELECT	COUNT(ReasonCdName) as ReasonCdName 		FROM SOHeaderHist WHERE ReasonCdName  is not null
SELECT	COUNT(RefSONo) as RefSONo 			FROM SOHeaderHist WHERE RefSONo  is not null
SELECT	COUNT(RlsWhseDt) as RlsWhseDt 			FROM SOHeaderHist WHERE RlsWhseDt  is not null
SELECT	COUNT(SalesRepName) as SalesRepName 		FROM SOHeaderHist WHERE SalesRepName  is not null
SELECT	COUNT(ShipLocName) as ShipLocName 		FROM SOHeaderHist WHERE ShipLocName  is not null
SELECT	COUNT(StatusCd) as StatusCd 			FROM SOHeaderHist WHERE StatusCd  is not null
SELECT	COUNT(SubType) as SubType 			FROM SOHeaderHist WHERE SubType  is not null
SELECT	COUNT(TaxAmt) as TaxAmt 			FROM SOHeaderHist WHERE TaxAmt  is not null
SELECT	COUNT(TaxExpAmt) as TaxExpAmt 			FROM SOHeaderHist WHERE TaxExpAmt  is not null
SELECT	COUNT(TaxStat) as TaxStat 			FROM SOHeaderHist WHERE TaxStat  is not null
SELECT	COUNT(TotalCost2) as TotalCost2 		FROM SOHeaderHist WHERE TotalCost2  is not null
SELECT	COUNT(TotalOrder) as TotalOrder 		FROM SOHeaderHist WHERE TotalOrder  is not null
SELECT	COUNT(UsageLocName) as UsageLocName 		FROM SOHeaderHist WHERE UsageLocName  is not null
