--Process Contact Updates in NV3.7 [Porteous$Contact]
UPDATE	[Porteous$Contact]
SET	--[timestamp] = VendUpd.[timestamp],
	--[No_] = VendUpd.[No_],
	[Name] = VendUpd.[Name],
	[Search Name] = VendUpd.[Search Name],
	[Name 2] = VendUpd.[Name 2],
	[Address] = VendUpd.[Address],
	[Address 2] = VendUpd.[Address 2],
	[City] = VendUpd.[City],
	[Phone No_] = VendUpd.[Phone No_],
	[Telex No_] = VendUpd.[Telex No_],
	[Territory Code] = VendUpd.[Territory Code],
	[Currency Code] = VendUpd.[Currency Code],
	[Language Code] = VendUpd.[Language Code],
	[Salesperson Code] = VendUpd.[Salesperson Code],
	[Country Code] = VendUpd.[Country_Region Code],
	[Last Date Modified] = VendUpd.[Last Date Modified],
	[Fax No_] = VendUpd.[Fax No_],
	[Telex Answer Back] = VendUpd.[Telex Answer Back],
	[VAT Registration No_] = VendUpd.[VAT Registration No_],
	[Picture] = VendUpd.[Picture],
	[Post Code] = VendUpd.[Post Code],
	[County] = VendUpd.[County],
	[E-Mail] = VendUpd.[E-Mail],
	[Home Page] = VendUpd.[Home Page],
	[No_ Series] = VendUpd.[No_ Series],
	[Type] = VendUpd.[Type],
	[Company No_] = VendUpd.[Company No_],
	[Company Name] = VendUpd.[Company Name],
	[Lookup Contact No_] = VendUpd.[Lookup Contact No_],
	[First Name] = VendUpd.[First Name],
	[Middle Name] = VendUpd.[Middle Name],
	[Surname] = VendUpd.[Surname],
	[Job Title] = VendUpd.[Job Title],
	[Initials] = VendUpd.[Initials],
	[Extension No_] = VendUpd.[Extension No_],
	[Mobile Phone No_] = VendUpd.[Mobile Phone No_],
	[Pager] = VendUpd.[Pager],
	[Organizational Level Code] = VendUpd.[Organizational Level Code],
	[Exclude from Segment] = VendUpd.[Exclude from Segment],
	[External ID] = VendUpd.[External ID],
	[Correspondence Type] = VendUpd.[Correspondence Type],
	[Salutation Code] = VendUpd.[Salutation Code],
	[Search E-Mail] = VendUpd.[Search E-Mail],
	--[Version No_] = VendUpd.[],
	[Last Time Modified] = VendUpd.[Last Time Modified] --,
	--[] = VendUpd.[E-Mail 2],
	--[Password] = VendUpd.[],
	--[Password Padding] = VendUpd.[],
	--[Login ID] = VendUpd.[],
	--[Notification Process Code] = VendUpd.[],
	--[Enablement Date] = VendUpd.[],
	--[Queue Priority] = VendUpd.[],
	--[Online User Type] = VendUpd.[],
	--[On Behalf Of] = VendUpd.[],
	--[Catalog Set] = VendUpd.[],
	--[eConnect User] = VendUpd.[],
	--[eConnect Password] = VendUpd.[],
	--[eConnect Default Whse] = VendUpd.[],
	--[eConnect Order Limit] = VendUpd.[],
	--[eConnect Preference 1] = VendUpd.[],
	--[eConnect Preference 2] = VendUpd.[],
	--[eConnect Preference 3] = VendUpd.[],
	--[eConnect Preference 4] = VendUpd.[],
	--[eConnect Preference 5] = VendUpd.[],
	--[eConnect Preference 6] = VendUpd.[],
	--[eConnect Preference 7] = VendUpd.[],
	--[eConnect Preference 8] = VendUpd.[],
	--[eConnect Preference 9] = VendUpd.[],
	--[eConnect User Type] = VendUpd.[],
	--[eConnect On Behalf Of] = VendUpd.[],
	--[eConnect Roles] = VendUpd.[],
	--[Drop Ship] = VendUpd.[]
FROM	[Porteous$Contact] INNER JOIN
	OpenDataSource('SQLOLEDB','Data Source=PFCERPDB;User ID=pfcnormal;Password=pfcnormal').PFCFINANCE.dbo.[tempERPVendUpdate] VendUpd ON
	VendUpd.[No_] = [Porteous$Contact].[No_] COLLATE Latin1_General_CS_AS



--select * from OpenDataSource('SQLOLEDB','Data Source=PFCERPDB;User ID=pfcnormal;Password=pfcnormal').PFCFINANCE.dbo.[tempERPVendUpdate]


--select *  into [tPorteous$Contact] from [Porteous$Contact]